// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBookingBackend.Data;

#nullable disable

namespace RoomBookingBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214091224_SeedRoomBooking")]
    partial class SeedRoomBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RoomBookingBackend.Models.RoomBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RoomBookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedBy = "Najwa",
                            CreatedAt = new DateTime(2026, 2, 14, 16, 12, 22, 551, DateTimeKind.Local).AddTicks(4040),
                            Date = new DateTime(2026, 2, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomName = "B201",
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            BookedBy = "Nando",
                            CreatedAt = new DateTime(2026, 2, 14, 16, 12, 22, 551, DateTimeKind.Local).AddTicks(4049),
                            Date = new DateTime(2026, 2, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomName = "B202",
                            Status = "Pending"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
